version: "3"

services: 
    web:
        container_name: apitoken
        restart: always
        build: .
        ports: 
            - "3000:3000"
        links:
            - mongo
        volumes:
            - .:/usr/src/app

    mongo:
        container_name: mongodb2
        image: mongo
        ports: 
            - "27018:27017"